### PR TITLE
Incorrect cwd fix

### LINKED ISSUE #13: isPathIgnored throwing exception
Keep getting this when I modify one project and then try to expand another project folder. Something seems to be setting `cachedIgnoreStatuses` to null?

atom-hg-indexof-is-null

### PR DESCRIPTION
**Pull request by mrstebo**
Seems to fix #13 

This also provides a bit of speed optimization due to not having to run the `hg` command on every open project.
This works assuming that every command being sent to `hg` contains the full path to the repository.

### CODE REVIEW

File: lib/hg-utils.coffee [hunk 1]
```diff
@@ -410,6 +414,21 @@ class Repository
...
+  # with the current repository.
+  #
+  # * `params` The params that are going to be sent to the hg command {Array}
+  #
+  # Returns a {Boolean} indicating if the rootPath was found in the params
+  isCommandForRepo: (params) ->
+    rootPath = @rootPath
+
+    paths = params.filter (param) ->
+      normalizedPath = path.normalize((param || ''))
```
Comment (victor-torres) [inline lib/hg-utils.coffee:427]: Sometimes I had got paths starting with `../`. I'm removing this characters somewhere but I'm not sure if it will cause any problem... I guess no. If I find any problem I'll let you know.

File: lib/hg-utils.coffee [hunk 2]
```diff
@@ -242,7 +242,11 @@ class Repository
       params = []
     if !util.isArray(params)
       params = [params]
-    child = spawnSync('hg', params)
+
+    return '' unless @isCommandForRepo(params)
```
Comment (victor-torres) [inline lib/hg-utils.coffee:246]: We should think about adding logs (debug?) across the code later. It would be easier to identify some bugs.

File: lib/hg-utils.coffee [hunk 3]
```diff
@@ -242,7 +242,11 @@ class Repository
...
+
+    options = { cwd: @rootPath }
+    child = spawnSync('hg', params, options)
```
Comment (victor-torres) [inline lib/hg-utils.coffee:249]: tree-view file diff/status stopped working here. Removed cwd options and it went fine. Do we really need cwd option since we're always passing the repository/file path to hg commands? 

I've also release v2.0.3 with your fixes :) 

Thanks for your support. I'll add a contributors section on readme.md and put your name/github account there.

Comment (mrstebo) [inline lib/hg-utils.coffee:249]: Awesome :smile: 
Without the cwd option I was running into the error message I mentioned in #13. It may just be a Windows thing?

Comment (victor-torres) [inline lib/hg-utils.coffee:249]: Could you try it again? I'm almost sure it was caused by the 'restart' needing after installing mercurial :P

Comment (mrstebo) [inline lib/hg-utils.coffee:249]: I already had mercurial installed, but I restarted anyway. Error is still there. Although the full path is there, it probably needs the cwd being specified so the command knows where the .hg file is???

Comment (mrstebo) [inline lib/hg-utils.coffee:249]: Also, spawnSync seems to be the main bottleneck for performance :persevere:

Comment (victor-torres) [inline lib/hg-utils.coffee:249]: Mercurial should take care of .hg file location since we're already telling him the repository/file path. May be something related to Windows only.

> $ hg --version
> Mercurial Distributed SCM (version 3.7.2)

Can you check if your hg is up to date?!

If updating it won't solve the problem, for now you could add a verification and if the platform is Windows, add the cwd option to spawnSync method. You also have to check if tree-view file status keeps working.

About the spawnSync performance, using an async version improves things? You're doing a great work. Feel free to open a new pull request if you need so.

Comment (mrstebo) [inline lib/hg-utils.coffee:249]: I can only assume if we return promises from `hgCommand` then we can probably get the same performance that the `GitRespositoryAsync` gets. Maybe create a new `hgCommandAsync` method specifically for the `HgRespositoryAsync` class?

I updated my hg a few days ago, so that should be fine. Think it might be a case of doing the platform check.
