### PR TITLE
Dirs with spaces

### LINKED ISSUE #34: Directories with spaces in them crash hg stat
Atom-hg runs hg stat for a specific directory.

If the root directory of the repository has spaces somewhere in the path, these are not correctly quoted on windows.

### PR DESCRIPTION
**Pull request by TomKemperNL**
Fixes #34, which was caused by the switch from spawnSync to asynchronous exec. 

exec doesn't accept a parameter array, so I flattened the arguments manually.

I'm pretty sure there are still edge-cases we're missing, but at least this is a little bit better.

### CODE REVIEW

File: lib/hg-utils.coffee [hunk 1]
```diff
@@ -268,6 +268,9 @@ class Repository
     return Promise.resolve('') unless @isCommandForRepo(params)
 
     flatArgs = params.reduce (prev, next) ->
+      if next.indexOf? and next.indexOf(' ') != -1
```
Comment (victor-torres) [inline lib/hg-utils.coffee:271]: @TomKemperNL you could have added the quotes every time without checking.
